Hot-fix ATE package install as part of vdp-meta
VDP-2608

This hot-fix is needed until vdp-meta approach is used to upgrade VDP
distributions. In this approach children packages of vdp-meta does not
specify versions of their dependencies (and only vdp-meta knows the exact
versions of all components).

vdp-ate requires /etc/default/board_profile environment file, which is
generated by vdp-core-base package during its configuration phase (i.e.
in postinst script).

The issue has place when vdp-meta is upgraded using 'apt-get install
vdp-meta' command. vdp-ate is not aware that vdp-core-base gets upgraded
as well (as the dependency is versionless and already satisfied by previous
installed version of vdp-core-base).

Since all dependencies are satisfied, apt-get resolves installation and
configuration in the next order:
1. Unpack vdp-core-base (which beforewards calls prerm and removes
/etc/default/board_profile file).
2. Unpack vdp-ate.
3. Configure vdp-ate. At this point vdp_ate_server service cannot start as
   env file does not exist.
4. Configure vdp-core-base, which finally generates the env file.

This hot-fix does not address the issue, but instead ignores the error
and allows systemd to restart vdp_ate_server.service later using its
retry mechanism.

diff --git a/data/debian/postinst b/data/debian/postinst
--- a/data/debian/postinst
+++ b/data/debian/postinst
@@ -24,4 +24,9 @@ test $? -eq 0 && echo "Ok" || echo "error: failed to set permissions of @ATE_WRI
 if [ "@ATE_INSTALL_SERVER_SERVICE@" = "ON" ]; then
     systemctl enable vdp_ate_server
     systemctl start vdp_ate_server
+    test $? -eq 0 || echo "warning: systemctl start vdp_ate_server returned $?. See \"systemctl status vdp_ate_server\" and " \
+                          "\"journalctl -xe -u vdp_ate_server\" for details. You may require to run vdp_ate_server service manually."
 fi
+
+# Ignore last command exit code
+exit 0
